server:
  port: 9010
spring:
  application:
    name: server-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.140.140:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-gateway
          uri: lb://server-shop-user
          order: 1
          predicates:
            - Path=/server-shop-user/**
          filters:
            - StripPrefix=1

        - id: product-gateway
          uri: lb://server-shop-product
          order: 1
          predicates:
            - Path=/server-shop-product/**
          filters:
            - StripPrefix=1

        - id: order-gateway
          uri: lb://server-shop-order
          order: 1
          predicates:
            - Path=/server-shop-order/**
          filters:
            - StripPrefix=1