server:
  port: 9010
  servlet:
    context-path: /shop-gateway
spring:
  application:
    name: server-shop-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"

      routes:
        - id: user-gateway
          uri: http://localhost:8060
          order: 1
          predicates:
            - Path=/server-shop-user/**
          filters:
            - StripPrefix=1

        - id: product-gateway
          uri: http://localhost:8070
          order: 1
          predicates:
            - Path=/server-shop-product/**
          filters:
            - StripPrefix=1

        - id: order-gateway
          uri: http://localhost:8090
          order: 1
          predicates:
            - Path=/server-shop-order/**
          filters:
            - StripPrefix=1